### ISSUE TITLE
MADS records without citeurns

### ISSUE THREAD

**Issue by cwulfman** [PerseusDL/catalog_data#117]
The following documents do not have `<mads:identifier type='citeurn']>` elements:

- mads/PrimaryAuthors/M/MADSTemplate.xml
- mads/PrimaryAuthors/P/Pausanias Lacon/viaf27455714.mads.xml
- mads/PrimaryAuthors/A/Archinus Historicus/viaf57001292.mads.xml

The first should probably be moved somewhere else; the other two have various other anomalies that suggest they slipped into production prematurely.

**Comment by AlisonBabeu** [comment]
Hi @cwulfman. The MADS template does not have a citeurn element in it because the citeurns have always been added automatically by the catalog system not manually so I felt no need to include an element in the template, which is meant to help people create records from scratch when needed.

I will add in the CITE URNs to the two other records.

**Comment by cwulfman** [comment]
Thanks! I'm loading the MODS and MADS automatically, and my script can't tell the difference between a template and a completed record.

**Comment by AlisonBabeu** [comment]
And somehow I missed completely that the MADSTemplate.xml is a file we no longer need so I"m deleting it, as the long-term MADS template my students have used is here: https://github.com/PerseusDL/catalog_pending/blob/master/templates/madsauthorrecordtemplate.xml.
