### ISSUE TITLE
tlg0007.tlg067 incorrect languages in tags?

### ISSUE THREAD

**Issue by lcerrato** [PerseusDL/catalog_data#153]
Hi,
I noticed while working on these files that 
http://data.perseus.org/catalog/urn:cts:greekLit:tlg0007.tlg067.perseus-grc1/atom

reads
`<ti:title xml:lang="grc">De liberis educandis</ti:title>`  where this should be Latin (lat)
and likewise
`<ti:label xml:lang="eng">De liberis educandis, Plutarchi Chaeronensis Moralia Vol I</ti:label>`

**Comment by lcerrato** [comment]
also here (same places) 
http://data.perseus.org/catalog/urn:cts:greekLit:tlg0007.tlg067.perseus-eng1/atom

**Comment by lcerrato** [comment]
note that when I create the cts work file, the labels for the English translations will read differently, as each book has a different title for the translation (neither use the Latin title)

**Comment by AlisonBabeu** [comment]
Interesting. The titles in catalog_data had in a few cases already been fixed, (I don't think that the ATOM files have ever been regenerated since the few first catalog_data creation five years ago). I've fixed any remaining titles in these files that had a language tagging issue. At some point I should probably do a mass language tagging fix, since all of the uniform titles automatically have the language English as an attribute, even though many of them are not.
