### ISSUE TITLE
Number of Aristotle works not displaying or supporting search by Latin translated titles

### ISSUE THREAD

**Issue by AlisonBabeu** [PerseusDL/catalog_data#45]
The list of works under Aristotle (http://catalog.perseus.org/catalog/urn:cite:perseus:author.204) includes many works that for some reason are only displaying the Greek title as well as supporting search by the Greek title. This seems strange because the MODS records have the Latin titles in them and are present in the Atom feeds (http://catalog.perseus.org/catalog/urn:cts:greekLit:tlg0086.tlg002). 

The CITE Table records for these works do not display the Latin titles.

**Comment by annakrohn** [comment]
It should be preferring uniform titles but it isn't.  I'll write up something to figure out exactly what is wrong and do a correction on the CITE works table.  It will get corrected in the next import since the change will need to percolate through the atom feeds, catalog database, and solr, just as a regular import would.

**Comment by annakrohn** [comment]
This is fixed in the latest catalog update.
