### ISSUE TITLE
CTS URN for De Rebus Bellicis

### ISSUE THREAD

**Issue by scotartt** [PerseusDL/catalog_data#8]
Title of work: De Rebus Bellicis
Author: Anonymi Auctoris De Rebus Bellicis

Edition: unknown text edition

Electronic resource: University of Oxford Text Archive - http://ota.ahds.ac.uk/desc/0309 

The OTA page has a download link to a ZIP file with an TEI header document, but the text body in a plain-text format. It is licensed as Creative Commons Attribution Non-commercial 3.0 and will be the version of the text used for conversion to CTS TEI XML with as much of the OTA header intact as possible. I will attach the OTA header in a separate comment, as well as worldcat entries in another comment on the issue.

**Comment by AlisonBabeu** [comment]
Dear all,

I have reopened this issue due to the fact that the STOA identifier I had assigned to this work was accidentally reassigned to another work by yours truly and now that the catalog update has gone live we actually have published a work with the CTS-URN stoa0354.stoa001 (http://catalog.perseus.org/catalog/urn:cts:latinLit:stoa0354.stoa001). Since this original issue was opened we have expanded how we create CTS-URNs to include other namespaces, so we have decided to give this work a CTS-URN utilizing the identifier from the Oxford Text Archive, so the updated CTS-URN for this work would be  urn:cts:latinLit:ota0309.ota001.opp-lat1, on the assumption that this is the first "edition" of this work under that OTA identifier.

I have used this new identifier in an updated MODS record and pushed it out to catalog_pending where it will be ingested into the catalog at the next update (https://github.com/PerseusDL/catalog_pending/tree/master/mods/Anonymous%20De%20Rebus%20Bellicis).

I apologize for the confusion, my mistake in reusing the identifier, and hope this makes sense.

Alison
