### ISSUE TITLE
need new edition-level MODS file for Kaibel edition of Athenaeus Deipnosophistae

### ISSUE THREAD

**Issue by balmas** [PerseusDL/catalog_data#9]
We need a new edition-level MODS file for the Epidoc version of the Athenaeus Kaibel edition. This digital edition is derived from the current P4 version http://data.perseus.org/texts/urn:cts:greekLit:tlg0008.tlg001.perseus-grc2 (it seems that maybe we're missing a catalog record for this too though...).

**Comment by AlisonBabeu** [comment]
Upon rechecking all of these files have made it into catalog_data (https://github.com/PerseusDL/catalog_data/tree/6e34ff1dc16290f854b4faa8bd4c16ef2d766f2a/mods/greekLit/tlg0008/tlg001) but none of them are showing up as live in the catalog. I'm wondering if this is due to the duplicate presence of CTS-URNs in the MODS records,

**Comment by AlisonBabeu** [comment]
The duplicate CTS-URN issue has been resolved and this edition now has a permanent catalog record (http://catalog.perseus.org/catalog/urn:cts:greekLit:tlg0008.tlg001.perseus-grc3) so I am closing this issue.
